[package]
name = "revo"
version = "0.1.0"
edition = "2024"

[dependencies]
revo-sys = { path = "../revo-sys" }
revo-macros = { path = "../revo-macros", optional = true }

[features]
default = ["macros"]
macros = ["revo-macros"]

[[example]]
name = "extension"
path = "examples/extension.rs"
crate-type = ["dylib"]
